services:
  ae-wallet-be:
    image: ae-wallet-be
    build:
      context: ./ae-wallet-be
      dockerfile: Dockerfile.dev
    container_name: ae-wallet-be
    ports:
      - "8443:8443"
      - "5005:5005"
    env_file:
      - .env
    networks:
      - ae-wallet-fe
  ae-wallet-fe:
    image: ae-wallet-fe
    build:
      context: ./ae-wallet-fe
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    networks:
      - ae-wallet-fe
    
networks:
  ae-wallet-fe:
    driver: bridge