services:
  ae-wallet-be:
    image: ae-wallet-be
    build:
      context: ./ae-wallet-be
      dockerfile: Dockerfile
    container_name: ae-wallet-be
    ports:
      - "8443:8443"
      - "5005:5005"
    env_file:
      - ./environment/db.env
      - ./environment/cors.env
      - ./environment/jwt.env
      - ./environment/ssl.env
    networks:
      - ae-wallet-fe
    restart: always
  ae-wallet-fe:
    image: ae-wallet-fe
    build:
      context: ./ae-wallet-fe
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - ae-wallet-fe
    restart: always
    
networks:
  ae-wallet-fe:
    driver: bridge
